// <auto-generated />
using LocalLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalLibrary.Migrations
{
    [DbContext(typeof(LibraryDBContext))]
    [Migration("20240414175934_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("LocalLibrary.Model.LibraryDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("LibraryName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("libraryName");

                    b.Property<string>("LibraryPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LibraryPath");

                    b.HasKey("Id");

                    b.ToTable("LibraryDBs");
                });
#pragma warning restore 612, 618
        }
    }
}
